version: "3"
services:
  api:
    build: ./api
    restart: on-failure
    container_name: api
    volumes:
      - ./api:/app
    depends_on:
      - db

  client:
    build: ./client
    restart: on-failure
    container_name: client
    volumes:
      - ./client:/app

  db:
    image: postgres
    restart: always
    container_name: db
    environment:
      POSTGRES_USER: 'basic-user'
      POSTGRES_PASSWORD: 'PASSWORD'
      POSTGRES_DB: 'basic'
    volumes:
      - ./pgdata:/var/lib/postgresql/data
